ecomers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_appe.urls')),
]

main_appe/urls.py
from django.urls import path,include
from main_appe import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home,name='home'),
    path('category_list',views.Category_list,name="category_list"),
    path('brands_list',views.Brands_list,name="brands_list"),
    path('product_list',views.Product_List,name='product_list'),
    path('search_product',views.search_products,name="search_product"),

    path('category_product_list/<id>',views.Category_Product_List,name='category_product_list'),
    path('brand_product_list/<id>',views.Brand_product_list,name="brand_product_list"),
    path('product_details/<slug>/<id>',views.Product_Details_page,name='product_details'),
    path('filter_products',views.filter_data,name='filter_products'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_appe/models.py
from django.db import models
from django.utils.html import mark_safe

# Create your models here.

class Banner(models.Model):
    image=models.ImageField(upload_to='banner_images')
    alt_text=models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def __str__(self):
        return self.alt_text
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />'%(self.image.url))

class Category(models.Model):
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='category_images')

    class Meta:
        verbose_name_plural = '2. Categorys'

    def __str__(self):
        return self.title
    def image_get(self):
        return mark_safe('<img src="%s" width="80" />'%(self.image.url))

class Brand(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='brand_images')

    class Meta:
        verbose_name_plural = '3. Brands'

    def __str__(self):
        return self.title

class Color(models.Model):
    title=models.CharField(max_length=100)
    color_code=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Colors'

    def color_get(self):
        return mark_safe('<div style="width:20px;height:20px; background:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title

class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '5. Sizes'

    def __str__(self):
        return self.title


class Product(models.Model):
    title=models.CharField(max_length=300)
    slug=models.CharField(max_length=300)
    detail=models.TextField()
    specs=models.TextField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    is_featured=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title

class ProductAttributes(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    size=models.ForeignKey(Size,on_delete=models.CASCADE)
    price=models.PositiveIntegerField(default=0)
    image=models.ImageField(upload_to='product_images',null=True)

    class Meta:
        verbose_name_plural = '7. ProductAttributes'

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.image.url))

    def __str__(self):
        return self.product.title

main_appe/views.py
from django.shortcuts import render
from .models import Category,Brand,Product,ProductAttributes,Banner
from django.http import JsonResponse,HttpResponse
from django.template.loader import render_to_string

# Create your views here.
def home(request):
    data = Product.objects.filter(is_featured=True).order_by('-id')
    banner = Banner.objects.all().order_by('-id')
    return render(request,'index.html',{"data":data,"banner":banner})

def Category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request,'category_list.html',{"data":data})

def Brands_list(request):
    data = Brand.objects.all().order_by('-id')
    return render(request,'brands_list.html',{"data":data})

def Product_List(request):
    data = Product.objects.all().order_by('-id')
    # category=Product.objects.distinct().values('category__title','category__id')
    # brand = Product.objects.distinct().values('brand__title',"brand__id")
    # colors=ProductAttributes.objects.distinct().values('color__title','color__id',"color__color_code")
    # sizes = ProductAttributes.objects.distinct().values('size__title','size__id')
    return render(request,'product_list.html',{
        "data":data,
        # 'category':category,
        # 'brand':brand,
        # 'colors':colors,
        # 'sizes':sizes
    })
def Category_Product_List(request,id):
    category = Category.objects.get(id=id)
    data = Product.objects.filter(category=category).order_by('-id')
    # category = Product.objects.distinct().values('category__title', 'category__id')
    # brand = Product.objects.distinct().values('brand__title', "brand__id")
    # colors = ProductAttributes.objects.distinct().values('color__title', 'color__id', "color__color_code")
    # sizes = ProductAttributes.objects.distinct().values('size__title', 'size__id')
    return render(request,'category_product_list.html',{
        'data':data,
        # 'category': category,
        # 'brand': brand,
        # 'colors': colors,
        # 'sizes': sizes
    })

def Brand_product_list(request,id):
    brand = Brand.objects.get(id=id)
    data = Product.objects.filter(brand=brand)
    # category = Product.objects.distinct().values('category__title', 'category__id')
    # brand = Product.objects.distinct().values('brand__title', "brand__id")
    # colors = ProductAttributes.objects.distinct().values('color__title', 'color__id', "color__color_code")
    # sizes = ProductAttributes.objects.distinct().values('size__title', 'size__id')
    return render(request,"brand_product_list.html",{
        'data':data,
        # 'category': category,
        # 'brand': brand,
        # 'colors': colors,
        # 'sizes': sizes
    })

# product details page
def Product_Details_page(request,slug,id):
    product = Product.objects.get(id=id)
    related_products = Product.objects.filter(category=product.category).exclude(id=id)[:3]
    return render(request,'product_details_page.html',{"data":product,"related_product":related_products})

# search function for home page
def search_products(request):
    qs=request.GET['q']
    data = Product.objects.filter(title__icontains=qs).order_by('-id')
    return render(request,'search_product.html',{'data':data})

# filter data by products
def filter_data(request):
    colors = request.GET.getlist('color[]')
    print(colors)
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    sizes = request.GET.getlist('size[]')
    minprice = request.GET['minprice']
    maxprice = request.GET['maxprice']
    allProducts=Product.objects.all().order_by('-id').distinct()
    allProducts = allProducts.filter(productattributes__price__gte=minprice)
    allProducts = allProducts.filter(productattributes__price__lte=maxprice)
    if len(colors) > 0:
        allProducts =allProducts.filter(productattributes__color_id__in=colors).distinct()
        print(allProducts)
    if len(categories) > 0:
        allProducts = allProducts.filter(category__id__in=categories).distinct()
    if len(brands) > 0:
        allProducts = allProducts.filter(brand__id__in=brands).distinct()
    if len(sizes) > 0:
        allProducts = allProducts.filter(productattributes__size_id__in=sizes).distinct()
    t = render_to_string('ajax/product_list.html', {'data': allProducts})
    # print(t)

    return JsonResponse({'data':t})

templates/ajax/product_list.html
 {% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_details' product.slug product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="{% url 'product_details' product.slug product.id %}">{{ product.title }}</a></h6>
						  <h6>Rs. {{product.productattributes_set.first.price}}</h6>

					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
    {% endfor %}

templates/brand_product_list.html
{% extends 'base.html' %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<div class="col-md-3">
		<!-- Filters -->
    	{% include "filters.html" %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_details' product.slug product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="{% url 'product_details' product.slug product.id %}">{{ product.title }}</a></h6>
						  <h6>Rs. {{ product.productattributes_set.first.price }}</h6>

					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="<?php echo $baseUrl; ?>/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

templates/brands_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if data %}
            {% for brands in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'brand_product_list' brands.id %}"><img src="{{ brands.image.url }}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="{% url 'brand_product_list' brands.id %}">{{ brands.title }} </a></h6>
			  </div>
			</div>
		</div>
            {% endfor %}
        {% endif %}
	</div>
</main>
{% endblock %}

templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		<?php
		for($i=1; $i<=6; $i++){
		?>
        {% if data %}
            {% for category in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'category_product_list' category.id %}"><img src="{{ category.image.url }}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="{% url 'category_product_list' category.id %}">{{ category.title }} <?php echo $i; ?></a></h6>
			  </div>
			</div>
		</div>
            {% endfor %}
        {% endif %}
		<?php } ?>
	</div>
</main>
{% endblock %}

templates/category_product_list.html
{% extends 'base.html' %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<div class="col-md-3">
		<!-- Filters -->
    		{% include "filters.html" %}
		</div>

		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row">
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_details' product.slug product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="{% url 'product_details' product.slug product.id %}">{{ product.title }}</a></h6>
						  <h6>Rs. {{ product.productattributes_set.first.price }}</h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="<?php echo $baseUrl; ?>/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

templates/filters.html
{% load static %}
<!--{{minMaxPrice}}-->
<script type="text/javascript" src="{% static 'product_filter.js' %}"></script>
			<h3 class="mb-4 border-bottom pb-1">Filters</h3>
<!--			filter for the price-->
			<div class="card mb-4">
				<h6 class="card-header">Price</h6>
				<div class="list-group list-group-flush">
					<li class="list-group-item">
						<input class="" type="range" value="{{minMaxPrice.price__min}}" min={{minMaxPrice.price__min}} max={{minMaxPrice.price__max}} id="rangeinpur"  oninput="maxprice.value=this.value">
						<p>Min= {{minMaxPrice.price__min}} -  Max= {{minMaxPrice.price__max}}</p>
					</li>
					<li class="list-group-item">
						Max : <input class="" type="number" value="{{minMaxPrice.price__min}}" onkeyup="rangeinpur.value=this.value" id="maxprice" min={{minMaxPrice.price__min}} max={{minMaxPrice.price__max}} />
						<button id="priceFilterButton" class="btn btn-info btn-sm pb-1">Filter</button>
					</li>
				</div>
			</div>
			<!-- Filter 1 -->
			<div class="card mb-4">
				<h6 class="card-header">Colors</h6>
				<div class="list-group list-group-flush">
                    {% for colors in colors %}
					<li class="list-group-item">
						<input class="filter-checkbox" type="checkbox" data-filter="color"    value="{{ colors.color__id }}" />&nbsp;
<!--						<button class="btn " style="background-color: {{ colors.color__color_code }};margin-top: -5px"></button>-->
						<button class="btn" style="background-color:{{ colors.color__color_code }};margin-top: -5px;"></button>

					</li>
                    {% endfor %}
				</div>
			</div>
			<!-- Filter 2 -->
			<div class="card mb-4">
				<h6 class="card-header">Categories</h6>
				<div class="list-group list-group-flush">
                    {% for category in category %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="category" value="{{ category.category__id }}"  type="checkbox" />&nbsp;
						{{ category.category__title }}
					</li>
                    {% endfor %}
				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Brands</h6>
				<div class="list-group list-group-flush">
                    {% for brand in brand %}
					<li class="list-group-item">
						<input class="filter-checkbox" value="{{ brand.brand__id }}" data-filter="brand" type="checkbox" />&nbsp;
						{{ brand.brand__title }}
					</li>
                    {% endfor %}

				</div>
			</div>
			<!-- Filter 3 -->
			<div class="card mb-4">
				<h6 class="card-header">Sizes</h6>
				<div class="list-group list-group-flush">
                    {% for sizes in sizes %}
					<li class="list-group-item">
						<input class="filter-checkbox" type="checkbox" data-filter="size"  value="{{ sizes.size__id }}" />&nbsp;
						{{ sizes.size__title }}
					</li>
                    {% endfor %}

				</div>
			</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
      {% for banners in banner %}
          {% if forloop.counter == 1 %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" class="active"></li>
            {% else %}
                  <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" ></li>
          {% endif %}
      {% endfor %}
  </ol>
  <div class="carousel-inner">
      {% for banner in banner %}
          {% if forloop.counter == 1 %}
            <div class="carousel-item active">
              {% else %}
                <div class="carousel-item ">
          {% endif %}
      <img src="{{ banner.image.url }}" class="d-block w-100" alt="...">
    </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
		{% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'product_details' slug=product.slug id=product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="#">{{ product.title }}</a></h6>
                  <h6>Rs. {{product.productattributes_set.first.price}}</h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product_list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

templates/product_details_page.html
{% extends 'base.html' %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Product Detail</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="{{ data.productattributes_set.first.image.url }}" src="{{ data.productattributes_set.first.image.url }}" class="card-img-top" alt="...">
		</div>
		<div class="col-md-8">
			<h3>{{ data.title }}</h3>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Price</th>
					<th>{{ data.productattributes_set.first.price }}</th>
				</tr>
				<tr>
					<th>Colors</th>
					<td>
                        {% for p_attribute in data.productattributes_set.all %}
						<button class="btn btn-lg" style="background-color: {{ p_attribute.color.color_code }}"></button>
                        {% endfor %}
					</td>
				</tr>
				<tr>
					<th>Sizes</th>
					<td>
                        {% for p_attribute in data.productattributes_set.all %}
						<button class="btn btn-outline-secondary btn-sm">{{ p_attribute.size.title }}</button>
                        {% endfor %}
					</td>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" class="form-control" />
			  <div class="input-group-append">
			    <button class="btn btn-primary btn-sm" type="button" id="button-addon2"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Brand</th>
					<td><a href="#">{{ data.brand.title }}</a></td>
				</tr>
				<tr>
					<th>Category</th>
					<td><a href="#">{{ data.category.title }}</a></td>
				</tr>
				<tr>
					<th>Specification</th>
					<td>{{ data.specs }}</td>
				</tr>
			</table>
		</div>
		<!-- Reviews -->
		<div class="col-md-6">
			<h3 class="my-3">Reviews - 4.5/5 <i class="fa fa-star text-warning"></i></h3>
			<div class="card">
				<div class="card-body" style="max-height: 400px; overflow: auto;">
					<blockquote class="blockquote text-right">
					  <small>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</small>
					  <footer class="blockquote-footer">User
					  	<cite title="Source Title">
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  		<i class="fa fa-star text-warning"></i>
					  	</cite>
					  </footer>
					</blockquote>
					<hr />
				</div>
			</div>
		</div>
	</div>
{#    related products#}
<h3 class="mt-4 mb-3 border-bottom">Related Products</h3>
        <div class="row">
				{% for product in related_product %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_details' product.slug product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="{% url 'product_details' product.slug product.id %}">{{ product.title }}</a></h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
</main>
<script src="https://cdn.jsdelivr.net/gh/igorlino/elevatezoom-plus@1.2.3/src/jquery.ez-plus.js"></script>
<script>
    $('#zoom_01').ezPlus();
</script>
{% endblock %}

templates/product_list.html
{% extends 'base.html' %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<div class="col-md-3">
		<!-- Filters -->
    {% include "filters.html" %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">Products</h3>
			<div class="row" id="filteredproducts">
            <p class="ajaxLoader">Loading ....</p>
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="{% url 'product_details' product.slug product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
					  <div class="card-body">
					    <h6 class="card-text"><a href="{% url 'product_details' product.slug product.id %}">{{ product.title }}</a></h6>
						  <h6>Rs. {{product.productattributes_set.first.price}}</h6>

					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><a href="<?php echo $baseUrl; ?>/products.php" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync"></i></a></p>
		</div>
	</div>
</main>
{% endblock %}

templates/search_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<main class="container my-4">
	<!-- Featured Products -->
	<h5 class="my-4 border-bottom pb-1"><span class="text-muted">Search Result For </span> "{{ request.GET.q }}"</h5>
	<div class="row">
		{% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="{% url 'product_details' slug=product.slug id=product.id %}"><img src="{{ product.productattributes_set.first.image.url }}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="#">{{ product.title }}</a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product_list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}